Repository Masaki-Yamanaka/frontend-developer-resources, pull requests merged in 2021-12, with the labels that each got.

#30 fix:sass導入
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/isr-demo.tsx
  pages/login.tsx
  pages/ssg-demo.tsx
  pages/ssr-demo.tsx
  styles/Home.module.scss
  styles/globals.css
  styles/globals.scss
  yarn.lock
Labels: 環境構築

#29 Update/#28 update directory composition
  pages/login.tsx
  src/components/functional/Test/Test.tsx
  src/components/functional/Test/index.ts
  src/components/model/user/UserAvatar/UserAvatar.module.css
  src/components/model/user/UserAvatar/UserAvatar.tsx
  src/components/model/user/UserAvatar/index.ts
  src/components/page/Top/Top.module.css
  src/components/page/Top/Top.page.tsx
  src/components/page/Top/Top.tsx
  src/components/page/Top/index.ts
  src/components/ui/Button/Button.module.css
  src/components/ui/Button/Button.tsx
  src/components/ui/Button/index.ts
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/pages/isr-demo.tsx
  src/pages/login.tsx
  src/pages/ssg-demo.tsx
  src/pages/ssr-demo.tsx
  tsconfig.json
Labels: 環境構築

#32 Feature/prettier
  .eslintignore
  .eslintrc.json
  .prettierrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/API.ts
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/subscriptions.ts
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/pages/isr-demo.tsx
  src/pages/login.tsx
  src/pages/ssg-demo.tsx
  src/pages/ssr-demo.tsx
  styles/Home.module.scss
  styles/globals.scss
  yarn.lock
Labels: 環境構築

#37 update: update schema
  amplify/backend/api/frontenddeveloperres/schema.graphql
Labels: サーバー

#39 update: update schema
  .graphqlconfig.yml
  amplify/backend/api/frontenddeveloperres/schema.graphql
  amplify/backend/auth/frontenddeveloperresd62a6bab/cli-inputs.json
  src/API.ts
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/subscriptions.ts
Labels: サーバー

#41 ログインユーザー情報をDynamoDBに送信
  .graphqlconfig.yml
  src/components/api/auth.ts
  src/components/api/index.ts
  src/pages/_app.tsx
  src/types/index.ts
Labels: サーバー, フロント

#43 仮でサイドバー作った
  src/components/ui/Button/Button.module.css
  src/components/ui/Button/Button.module.scss
  src/components/ui/Button/Button.tsx
  src/components/ui/Button/index.ts
  src/components/ui/PageLink/PageLink.module.scss
  src/components/ui/PageLink/PageLink.tsx
  src/components/ui/PageLink/index.ts
  src/components/ui/SideBar/SideBar.module.scss
  src/components/ui/SideBar/SideBar.tsx
  src/components/ui/SideBar/index.ts
  src/pages/_app.tsx
  src/types/index.ts
Labels: フロント

#44 ユーザー情報をグローバルステートに保存する
  .graphqlconfig.yml
  src/components/api/auth.ts
  src/components/model/auth/Auth.tsx
  src/components/model/auth/index.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/types/index.ts
Labels: フロント

#57 feat: update graphql schema
  amplify/backend/api/frontenddeveloperres/schema.graphql
Labels: サーバー

#58 Feat/implement top page
  src/components/page/Top/Top.module.css
  src/components/page/Top/Top.module.scss
  src/components/page/Top/Top.page.tsx
  src/components/page/Top/Top.tsx
  src/components/page/Top/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: フロント

#59 投稿のリスト表示まで実装
  .graphqlconfig.yml
  next.config.js
  src/API.ts
  src/components/api/post.ts
  src/components/model/post/PostList/PostList.module.scss
  src/components/model/post/PostList/PostList.tsx
  src/components/model/post/PostList/index.ts
  src/components/page/Top/Top.tsx
  src/components/ui/Image/Imgae.tsx
  src/components/ui/Image/index.ts
  src/graphql/mutations.ts
  src/graphql/queries.ts
  src/graphql/subscriptions.ts
  src/types/index.ts
Labels: フロント

#60 Feat/create post feature
  src/components/api/auth.ts
  src/components/api/post.ts
  src/components/hooks/useCurrentUser.tsx
  src/components/model/post/PostCreateForm/PostCreateForm.tsx
  src/components/model/post/PostCreateForm/index.ts
  src/components/model/post/PostList/PostList.tsx
Labels: フロント

#61 Feat/create post feature
  src/components/hooks/usePost.tsx
  src/components/model/post/PostList/PostList.tsx
  src/components/page/Top/Top.tsx
Labels: フロント

#62 【トップ画面】記事編集機能の実装
  src/components/api/post.ts
  src/components/model/post/PostCard/PostCard.module.scss
  src/components/model/post/PostCard/PostCard.tsx
  src/components/model/post/PostCard/index.ts
  src/components/model/post/PostList/PostList.tsx
  src/components/model/post/PostList/index.ts
  src/components/model/post/PostUpdateForm/PostUpdateForm.tsx
  src/components/model/post/PostUpdateForm/index.ts
  src/components/page/Top/Top.module.scss
  src/components/page/Top/Top.tsx
Labels: フロント

#63 【TOP画面】記事削除機能を実装
  src/components/api/post.ts
  src/components/model/post/PostDeleteButton/PostDeleteButton.tsx
  src/components/model/post/PostDeleteButton/index.ts
  src/components/page/Top/Top.tsx
  src/types/index.ts
Labels: フロント

#65 update: update react hook form
  amplify/backend/api/frontenddeveloperres/schema.graphql
  package.json
  yarn.lock
Labels: 環境構築
